version: '3'
services:


 # Nginx server configuration   
  web:
    network_mode: bridge
    image: nginx:1.17
    container_name: webserver
    depends_on:
      - docker-mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - ./webcontent:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"

 # Php-fpm configuration
  php:
    network_mode: bridge
    build:
     context: ./dockerfile
    volumes:
      - ./webcontent:/var/www/html
      - ./php:/usr/local/etc/php/php.ini

 # Mysql configuration
  docker-mysql:
    image: mysql:5.7
    network_mode: bridge
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    container_name: docker-mysql-demo
    restart: always
    environment:
        - MYSQL_DATABASE=docker_demo
        - MYSQL_ROOT_PASSWORD=root123
    ports:
        - "33069:3306"
    volumes:
        - ./dbdata-demo:/var/lib/mysql
    
volumes:
  dbdata:
